POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearereeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZjJhZmRiMGE1MzFiOTQ2YmNiMzNjMGYiLCJpYXQiOjE1OTY2NTMyMjF9.jGJY1EaSypClCAa5FXMCzWqBdv9a7zkAgzAIwXBikbo


{
    "url": "www.boom.com",
    "title": "boom boom?",
    "author": "boom one",
    "id": "5f29ce7757d9850f79768fc5"
}
